### PR TITLE
[WIP] Windows Open With Support

### PR DESCRIPTION
**Pull request by CrossR**
Partial fix for #598.

This implements the Windows side of this, I'm not sure if other platforms have a similar issue.
Does this by adding the needed registry keys, and updating the opening of files to work for the new argument list.

Also added a fix for #344 whilst I was in this area.

I'm not especially a JS dev, so I need some advice on cleaning up the `BuildSetupTemplate.js`. Its functionally working, but its not the neatest code.
Similarly for the way I've changed main, it works but its not the nicest.

Oh, and what file types should we support right now? So far I've added text and JavaScript/TypeScript files, but there is obviously a tonne more we could add.

### CODE REVIEW

**Comment by CrossR** [comment]
Also I need to work out how to get the desktop icon working for this.
The icon is there since its working for .vim files and the app itself, it must just be the link to the icon that I've messed up.

**Comment by extr0py** [comment]
Wow, this is awesome! Thanks for putting this together, @CrossR !

I was just trying this on Windows and it's really cool to have the shell integration hooked up. I could see it improving my workflow on Windows for sure.

> I'm not especially a JS dev, so I need some advice on cleaning up the BuildSetupTemplate.js. Its functionally working, but its not the neatest code.

I don't really see any problems with it. As long as it is still relatively simple and easy to understand what is going on, that should be fine. The only piece that confused me a bit was that we were re-injecting the {{RegistryKey}} placeholder each time we replaced it, and then file add the closing line. We could potentially build up that registry key section in its entirety, and then just replace {{RegistryKey}} placeholder with the whole section. Not a requirement though to change, just thinking out loud - I'm fine with it as it is.

I really like that you pulled out the file extensions into a separate object - making it easy to configure this later.

> Oh, and what file types should we support right now?

Just a few off additional ones off the top of my head:
- `.md`: `Markdown Files`
- `.json`: `JSON Files`
- `.jsx`: `JavaScript Files`
- `.tsx`: `TypeScript Files`

I'm sure we'll keeping adding more as we go :)

> Also I need to work out how to get the desktop icon working for this.

It looks like the problem here is this setting:
```
Root: HKCR; Subkey: "${prodName}${ext}\\DefaultIcon"; ValueType: string; ValueName: ""; ValueData: "{app}\\images\\oni.ico"; Tasks: registerAsEditor;
```

The image path is a bit more nested in our install directory - it looks like it should be this instead:
```
{app}\resources\\app\\images\\oni.ico
```

> Similarly for the way I've changed main, it works but its not the nicest.

Unfortunately this change wasn't working for me. It might not hit that `app.on('ready')` path in all cases.

There's another place we do the slice of the arguments:
```
    const shouldQuit = app.makeSingleInstance((commandLine, workingDirectory) => {
        createWindow(commandLine.slice(2), workingDirectory)
    })
```

So I think we should pull your code to a helper method - like `removeExecutableFromArguments`, and that can do the logic that you added - and then we'd use it in both places. The logic looks reasonable to me, the only thing we might want to change is the `process.argv.length === 2` condition - I wonder there are cases where we could get multiple files?

Hope that helps. Nice work - thanks again for putting this together! It really makes Oni feel more like it 'belongs' on Windows and isn't just an afterthought.

**Comment by extr0py** [comment]
I merged the `package.json` for you - it was a conflict with my change to turn off the asar packing. The `oni.ico` path will still need to be updated in the script.

**Comment by CrossR** [comment]
Got the image working now, it was just because I was using the path for the source code, rather than the installer location. It will probably need changing quite soon, as I assume the folder will move once the asar stuff is added back?

Got those other file types added, and tested that its easy enough to manually add more if a user wanted via the Windows interface.

Does look very nice just having the icons all sat there!
Directory Image

Just need to work out why I can't seem to open files once you use the Open With loading...
It gives an error of "No matching Autocommands", but works fine if I open Oni normally.

**Comment by extr0py** [comment]
> It will probably need changing quite soon, as I assume the folder will move once the asar stuff is added back?

I think it will actually take some time to bring back the 'asar' packaging - unfortunately the behavior of the out-of-the-box asar packager actually increases the package size! So it will take some investigation and perhaps a custom packing strategy to make things work. I added a note in #350 to remind me to update the icon when we bring that back.

> Does look very nice just having the icons all sat there!

Ya, that's awesome! 👍 👍 

> Just need to work out why I can't seem to open files once you use the Open With loading...
It gives an error of "No matching Autocommands", but works fine if I open Oni normally.

Interesting - I'll see if I can repro this in a bit.

**Comment by CrossR** [comment]
Looks to be something to do with the way the first file is opened, which is via the function I wrote...

If I try and open one file it fails. If I try and open 4 files, the first fails and the three after are fine.

**Comment by extr0py** [comment]
> If I try and open one file it fails. If I try and open 4 files, the first fails and the three after are fine.

It seems like it's working for me now, after trying it (rebuilding the installer and everything):
- If I select _multiple files in explorer_ and Open, it actually opens 3 instances of Oni. It's kind of weird but at least all the files are opened (and it might be just how explorer behaviors)
- If I open _multiple files from the command line_, they all get opened, but they aren't visible in the "buffer line" until I start cycling through them (and the title says '1 of N').

Opening a single file seems to work fine for me - both from explorer and the command prompt.

Sounds like I'm seeing different behavior than you, though! Trying to figure out why..

A couple questions:
- By fails, do you mean the file doesn't load at all?
- Are you opening from explorer or the command line?

I'm excited to get this change in, it's so cool to see the icons hanging out in explorer now 😄

**Comment by CrossR** [comment]
Hmm I'll have a look into those two cases, I'm not sure. I don't know if Explorer calls a single command for each file (which it looks like its doing if there is multiple instances of Oni) or if it passes an array of items.

Might be the sort of thing that gets sorted if more complex tab management is implemented (ie dragging a tab out of the Oni tab bar to make a new instance of Oni etc). The second case just sounds like something isn't fully getting updated.

> By fails, do you mean the file doesn't load at all?
Are you opening from explorer or the command line?

Yep, the file doesn't load at all.
I'm opening a file via the explorer, the issue comes if I then open a second file in Oni. Ie Double click file > Oni Opens with File > Menu > Open File > Select File > Doesn't Open. The first file loads fine, the second doesn't load at all.

**Comment by extr0py** [comment]
> Yep, the file doesn't load at all.
I'm opening a file via the explorer, the issue comes if I then open a second file in Oni. Ie Double click file > Oni Opens with File > Menu > Open File > Select File > Doesn't Open. The first file loads fine, the second doesn't load at all.

Got it, thanks for the clarification, I can hit the same thing now. I'll try and look at it a bit tomorrow morning.

**Comment by extr0py** [comment]
Ah, I just realized this is due to missing a space after `:tabnew` in the work I did to reconcile Open Files... So not related to the installer / arguments at all.

This line:
```
executeVimCommandForMultipleFiles(":tabnew", files)
```

Needs to be:
```
executeVimCommandForMultipleFiles(":tabnew ", files)
```

Sorry about that, not sure how I missed that. I'll send out a PR for the fix. I found I could reproduce this without installing, by opening a file, and then opening multiple files.

Besides that, I think this is good to go - was there anything else you wanted to look at, @CrossR ? I'm planning on pushing out a new release this weekend and it would be great to have this in there!

**Comment by extr0py** [comment]
Opened #621 to track fixing that `:tabnew ` vs `:tabnew` regression.

**Comment by CrossR** [comment]
There is two other parts to clean up, but I think they can be moved into a separate issue, as I think this would be useful to get into the next release.

* Opening multiple files into a single instance of Oni if multiple files are highlighted.
* Fixing the command line opening so it correctly opens multiple files into individual visualised tabs.

Do you want me to merge the `:tabnew` change into this branch or should I leave them separate?

**Comment by extr0py** [comment]
> There is two other parts to clean up, but I think they can be moved into a separate issue, as I think this would be useful to get into the next release.

Sounds good to me! These both sound like incremental issues, given that neither scenario would've been enabled prior to this change.

> Do you want me to merge the :tabnew change into this branch or should I leave them separate?

Nah, that's okay - I merged it in with #621 . I'll go ahead and merge this in now (so we'll have both fixes in master).

**Comment by extr0py** [comment]
@CrossR - merged! This is a huge improvement for the Oni experience on Windows. I'm really glad we have this functionality now - thanks for your contribution!

**Comment by extr0py** [comment]
FYI, @CrossR , as a thank you, I put a small bounty on this issue:
https://www.bountysource.com/issues/43751451-windows-installer-add-option-to-add-oni-to-path

So make sure to go claim that 😄

**Comment by CrossR** [comment]
Cheers! Thanks for letting me help out on a great project!

**Pull request merged**
