### PR TITLE
FIXED ISSUE #642 - ADDED missing mappings

### PR DESCRIPTION
**Pull request by justjoeyuk**
inoremap wasn't working with the shift key so added the missing mappings.

### CODE REVIEW

**Comment by justjoeyuk** [comment]
Messed up the first PR. This should do it. References #642

**Comment by extr0py** [comment]
Just tried this out - unfortunately it looks like there is a regression. The <C-P> detection to open the command palette no longer works (since now we are adding the `S` in). Vim seems to treat `<C-P>`, `<C-S-p>`, and `<C-S-P>` the same as far as I can tell, but Oni sees them as different currently.

It seems like there are a couple possibilities to fix this:
- Only append `S-` if the character is longer than 1 (a compound key, like `space`)
- Change the hardcoded key binding in `NeovimEditor.tsx` to be recognize the new key chord (`<C-S-P>` instead of  `<C-P>`. Ideally, our input recognition would treat these equally, but that would be a more in-depth fix.

**Comment by cyansprite** [comment]
> Vim seems to treat <C-P>, <C-S-p>, and <C-S-P> the same as far as I can tell, but Oni sees them as different currently.

As far as I know neovim itself doesn't know the difference between <c-p> and <c-P>, <c-s-p> doesn't work either, if it has c- it just looks at the letter not the case, m-p and m-P ARE case sensitive though.

**Comment by extr0py** [comment]
> As far as I know neovim itself doesn't know the difference between <c-p> and <c-P>,<c-s-p> doesn't work either, if it has c- it just looks at the letter not the case, m-p and m-P ARE case sensitive though.

Hmm, I just tested this (on Windows):
- `nnoremap <C-a> :echo '<C-a>'<CR>`

And I tried it for <C-A> - at least in my testing, Neovim seemed to differentiate between the `<C-A>` and `<C-a>` case.

**Comment by justjoeyuk** [comment]
@extr0py I've had to use <S-C-P> as the mapping prepends "S" onto the command.

**Comment by extr0py** [comment]
Thanks @justjoeyuk !

I just tested this out - the 'Command Palette' (tasks) opens up fine now, but unfortunately I can't enter uppercase numbers into it. I think this is due to the `evt.preventDefault` we do with the shift key - could we remove that `preventDefault` for the time being? We use it for the `alt`/`ctrl` keys to not conflict with global keyboard shortcuts/accelerators, but I don't think we need it for the shift key (and it breaks that 'Command Palette' case).

**Comment by justjoeyuk** [comment]
@extr0py Awesome, sorry for the ignorant attempts, this is all a learning experience for me - first time with TypeScript (and neovim, for that matter!)

**Comment by extr0py** [comment]
> Awesome, sorry for the ignorant attempts, this is all a learning experience for me - first time with TypeScript (and neovim, for that matter!)

Oh no problem! Jumping in and pushing up code is the best way to learn (IMO). Thanks for taking time to dig into the codebase 😄 I really appreciate the contributions.

I think the fix here should be relatively straightforward - we can just remove the `evt.preventDefault` in the shift case, and that should address the remaining issue. After that, should be good to go in!

**Comment by justjoeyuk** [comment]
@extr0py Sorry for the delay, long weekend! Done.

**Comment by extr0py** [comment]
> @extr0py Sorry for the delay, long weekend! Done.

Haha no worries, thanks for updating it! I just tried it out and it's working great. I'll bring it in once the build is complete-

**Comment by extr0py** [comment]
Merged! Thanks for the contribution, @justjoeyuk !

**Pull request merged**
