### PR TITLE
Fix #343, install to Oni/ rather than oni/ on Windows

### LINKED ISSUE #343: Windows Installer: Fix Casing of `Oni`
Currently in 0.2.1, the Windows installer installs Oni to `C:\Program Files (x86)\oni`. It should be `C:\Program Files (x86)\Oni` instead.

### PR DESCRIPTION
**Pull request by keforbes**
I have no idea if this works (no Windows box to test on) but it seems reasonable to me.  I'm really just committing this Pull Request to see how Appveyor treats it. :smile:

### CODE REVIEW

**Comment by keforbes** [comment]
Build succeeded.  Would anyone be willing to test the output from this build?

**Comment by extr0py** [comment]
Awesome! I'll test it out tomorrow 😄

**Comment by extr0py** [comment]
I tested it out in Windows, and it looks much improved! Good idea to use that build metadata, so we don't have to duplicate the name (and removing the existing duplication).

I still see a few of places where `oni` shows up instead of `Oni`, which looks out of place in Windows.
image

image
image

I'm thinking it just makes sense to set `"AppName": prodName` so it updates all the entries needed.

**Comment by extr0py** [comment]
Thanks for your help with this! It will definitely improve the Windows experience.

**Comment by keforbes** [comment]
I changed the case of the Start Menu entry.  I'm afraid to change `"AppName"` to `prodName` globally though.  I know Windows isn't case-sensitive but I'm afraid it may have unintended consequences.

**Comment by extr0py** [comment]
Sure, I can try making that later and testing it out.

**Comment by extr0py** [comment]
I'll merge this in now - thanks for your help with this!

**Pull request merged**
