### PR TITLE
WIP: Fix for #312 - Add electron-packager to create release binaries

### PR DESCRIPTION
**Pull request by extr0py**

### CODE REVIEW

**Comment by extr0py** [comment]
Need to switch to `electron-builder`

**Comment by keforbes** [comment]
I think you should do a new release as soon as you get this working.  Release binaries will be really cool!

**Comment by extr0py** [comment]
Sounds like a plan - I'm hoping to have this all set by the weekend - perfect time for a new release!

**Comment by extr0py** [comment]
Will need a couple of follow up issues for this:
- Move some `dependencies` to `devDependencies` if they are being bundled in the webpack `bundle.js`, so they are not included twice
- Create `x64` build for Windows

**Comment by extr0py** [comment]
There are still some improvements we can make here, but we can track them as separate issues. I'm searching the first binary release will be a bit rocky, but we can continue to improve.

**Pull request merged**
