### PR TITLE
[Cleanup] change lists of else-if statements to switch statements

### PR DESCRIPTION
**Pull request by keforbes**
I had intended to only add a clause for the `set_icon` event so we wouldn't get the `Unhandled command: set_icon` warning anymore.  The `set_title` event tells us the window title to set, the `set_icon` event just tells us the title to use when the window is minimized.  Even the Neovim docs say:
```
In windowing systems not distinguishing between the two, "set_icon" can be ignored.
```

After making that change though, I felt compelled to change the list of `else if` statements into a `switch` statement.  I then looked for more occurrences of these lists of `else if` statements and only found one other offender.

So yeah, functionally, this Pull Request does nothing.  It just cleans up some annoyances in the code I've been wanting to address.

### CODE REVIEW

**Comment by bert88sta** [comment]
Ive heard that hash tables aren't more efficient than switch cases in JS,
is this true because hash tables are implemented differently or because
switch statements are optimized into a hash table

**Comment by bert88sta** [comment]
Just asking because in python this would all go into a dictionary lookup.

**Comment by keforbes** [comment]
It's my understanding that switch statements are still preferred in javascript when there are more than 3 conditions.
http://stackoverflow.com/questions/2922948/javascript-switch-vs-if-else-if-else
http://archive.oreilly.com/pub/a/server-administration/excerpts/even-faster-websites/writing-efficient-javascript.html
https://www.safaribooksonline.com/library/view/high-performance-javascript/9781449382308/ch04s02.html

Of course, with all that said, I really did it because I find switch statements easier to read. :laughing:  I doubt these methods were performance bottlenecks.

**Comment by bert88sta** [comment]
Interesting, I've seen some tests where larger lists  (100) in switch
statements are slower than object lookup

**Comment by keforbes** [comment]
Oh definitely, object lookup would be faster than `else-if` or `switch` statements.  I don't think it's worthwhile to create an object of callback functions for this scenario though.  Like I said, I doubt this is a performance bottleneck, I just find it easier to read.

**Comment by extr0py** [comment]
> Of course, with all that said, I really did it because I find switch statements easier to read. 😆

Thanks for doing this refactoring! Agreed 👍 The big if..else blocks are pretty annoying. Sometimes they start out as just a condition or two and then grow organically out of control.

**Pull request merged**
