### PR TITLE
[WIP] CursorLine and CursorColumn externalized

### PR DESCRIPTION
**Pull request by bert88sta**
I'll start this off by saying I have no idea how to get rid of duplicate commits and also the older ones. I tried a generic rebase to upstream/master, which failed, and then I went in and somehow duplicated the commits that I actually made... :(

Any help with this would be appreciated.

As for the actual content, I'd like your input on what could be done better and how. I didn't know exactly what direction to go, so I just kind of imitated the surrounding code.

### CODE REVIEW

**Comment by keforbes** [comment]
As far as the duplicate commits go, next time try creating a new branch and creating a Pull Request from that branch.  A Pull Request includes your full branch, not specific commits, and this Pull Request is from your `master` branch, which has all your previous commits as well.

In the future, before committing your changes, create a new branch
```
git checkout -b my-new-feature
```
Then add your changes and commit
```
git add <changed files>
git commit -m "with a message"
```
Note that when pushing changes to a new branch, your origin repo won't know about that branch yet.  So tell git to create a corresponding branch on its server along with your push.
```
git push --set-upstream origin my-new-feature
```

Now when you login to GitHub it should tell you "hey! you pushed to a new branch! do you want to Compare & Pull Request?".  That compare should only show the changes pushed to this new branch.

**Comment by keforbes** [comment]
Also, since you said you couldn't get the rebase to work, here are the steps I follow to rebase.  Hopefully this will work for you next time.

When there are changes to extr0py's main repo you'll need to pull them into your fork.
```
git fetch upstream
```
This will download the changes from extr0py's main repo to your disk.

Then tell git to apply those changes to your local repo.
```
git rebase upstream/master
```
This will apply extr0py's changes to your local repo on disk.

Then tell git to push those changes to your GitHub fork.
```
git push
```
After that, if you login to GitHub it should tell you that your branch is "even" with extr0py's branch.

**Comment by bert88sta** [comment]
I tried to rebase to upstream master but there were conflicts,  and when I
resolved them it said there weren't any changes...  Git is 2 hard 4 me.

**Comment by keforbes** [comment]
While it might say there aren't any changes, the line above probably said "your branch is ahead of origin/master by <N> commits".  That's where `git push` would push the rebase without adding any new "changes".

**Comment by bert88sta** [comment]
I've made a cleaner version over in #219

**Pull request closed without merging**
