### PR TITLE
Upgrade Neovim binaries to 0.2.0-828-g11b08bb0

### PR DESCRIPTION
**Pull request by extr0py**

### CODE REVIEW

**Comment by extr0py** [comment]
Fix #287

**Comment by justinmk** [comment]
I'm surprised the nvim tree is copied to oni's source tree. Any plans to do that at build-time instead? Or instead expect the user to have an existing nvim?

**Comment by extr0py** [comment]
Yes, for sure, I'd prefer to make this build-time instead - I'd like to build and package both the Windows and OSX binaries so it is a one-step process for install (like VimR) on those platforms. 

I have #123 tracking this - unfortunately I just haven't had time to pursue it in-depth, so I took the shortcut of checking in the built binaries.

**Comment by extr0py** [comment]
Also #99 for the OSX pre-built binary.

**Pull request merged**
