### PR TITLE
WIP: #201 - External Status Line

### PR DESCRIPTION
**Pull request by extr0py**
This is work for the following:
- Create an API plugin for StatusBar
- Create state + React component for StatusBar (which will involve some DOM changes / changes to how we render the Neovim piece of the UI)

In addition, I'd like to create a couple of sample status bar implementations:
- A `git` status bar component to show the current branch
- A `weather` example to show the current weather

Once the external UI is available, we can also plug that into the core work above.

### CODE REVIEW

**Comment by bert88sta** [comment]
Anything i could do to speed this up for you? I'm stoked that this has been started, but I'm not too familiar with how the plugin-host business works... Always a first time to learn I suppose

**Comment by extr0py** [comment]
The initial work will be a bit hard to parallelize - but there is some help I'll need shortly for this:

1) Some example plugins leveraging the status bar - I want to include a git integration out of the box, but also an example of something more interesting like a github notifications or weather statusbar plugin

2) Improving our documentation - our README.md is a bit hard to digest at the moment. I want to have a more concise demo gif / youtube video, and then distill some of the information in a better format (like a [gitbook](https://www.gitbook.com/@extr0py/dashboard))

**Comment by bert88sta** [comment]
Just testing this as you go, I definitely get some weirdness with text selection

**Comment by extr0py** [comment]
Oh ya, it's in a bad state right now, I gutted the whole UI temporarily to create an <EditorHost /> component. That will open the door for some really interesting UI integrations, after this work is done-

**Comment by bert88sta** [comment]
I don't actually know if the work you're doing on changing the UI into a component is going to help with the gui-tabline, but if you think it will let me know. Most of the actual vim boilerplate isn't too bad to get the information we need for an external tabling

**Comment by extr0py** [comment]
Thanks @bert88sta ! Yes, unfortunately I haven't been able to spend much time on this PR - but the changes will definitely help us. The UI will be in a more sane format so that we can add something like the tabline above, and be able to have some first-class styling for it.

With the component-ized UI:
```
   return <div className="container vertical full">
             <div className="container full">
                <EditorHost editor={this.props.editor} />
                <Cursor />
                <CursorLine lineType={"line"} />
                <CursorLine lineType={"column"} />
                <SignatureHelpContainer />
                <QuickInfoContainer />
                <SignatureHelpContainer />
                <MenuContainer />
                <AutoCompletionContainer />
            </div>
            <div className="container fixed">
                <StatusBar />
            </div>
          </div>
```

We'd be able to easily add a `<TabBar />` at the top of the UI. The other pieces that would be helpful would be thinking about what sort of state we need in the redux store (certainly an array of `TabInfo` - which would have things like `fileName`, `isModified`, maybe `filetype` for an icon), and then how to populate that state from Neovim

**Comment by bert88sta** [comment]
Neovim API has several functions for getting info about the tab bar and tab pages. I *think* the only "global" tab-info function is the one that lists the IDs of the tabs from left to right, the rest are info about the current tab. I'll try to put something together soon

**Comment by extr0py** [comment]
This one got crazy to merge, so I ported over the work into a new PR: #444. Tracking the ideas around tab lines in #361.

**Pull request closed without merging**
