### PR TITLE
Extr0py/16 use init vim

### PR DESCRIPTION
**Pull request by extr0py**
- WIP for #16 

- Use runtime paths instead of generating init.vim
- PENDING: Add option to use own config instead of defaults

### CODE REVIEW

**Comment by extr0py** [comment]
@darkwater - I think this is getting closer now. Your suggestion to use runtime paths instead of overriding init.vim is implemented, so I think that should be helpful. 

In addition, there's also a configuration option 'oni.useDefaultConfig' which defaults to true, but since the chosen defaults might conflict, this prevents those from being added to the runtimepath.

**Comment by extr0py** [comment]
Remaining work is to fix outstanding build issues and add an entry in the readme / faq documenting this option.

**Comment by jordwalke** [comment]
Looking forward to this! I've curated a very specific [vim config](https://github.com/jordwalke/VimBox) to create a modern editor feel and I'm looking forward to trying it with `oni`.

**Comment by jordwalke** [comment]
I like the idea of either using everything out of the box, or a completely from-scratch config. The odds of my plugins conflicting with the built in ones is so great, that it's probably better to just have them be separate (at least to start with).
When I try this pull request, I get an error in the console (missing `init_template.vim` or something).

**Comment by extr0py** [comment]
@jordwalke - the config looks really cool! 

> I like the idea of either using everything out of the box, or a completely from-scratch config. 

Yes, same here. I want to make sure the out-of-box experience is on point, and that the first time you launch the editor it _just feels good_. The first time I started VIM it felt like it was a wild beast that I would need to tame or something.... whereas installing and launching Atom was a very pleasant experience. Hopefully that makes drawing new people to modal editing easier...

And then of course it's important for VIM veterans to be able to use their finely-honed and crafted config with no friction, and still experience some of the UI benefits.

**Comment by extr0py** [comment]
Make sure to set `oni.useDefaultConfig` to false in your config.json to try this out :) 

If you see that the screen 'sticks' and waits for keypress on launch, that's an indication that something went wrong while loading init.vim - unfortunately Neovim doesn't bubble up the errors on launch, at the moment. Keep me posted if you see any issues like that.

**Comment by jordwalke** [comment]
Yes I like the idea of an out of box awesome experience even if people quickly disable it to get their own config. It sets the bar and shows people "yes you can create an amazing, modern experience with Vim".  They will poke around into how the out of box experience was achieved and start moving the best parts to their own config.

**Pull request merged**
