### PR TITLE
Move background to React component (#314)

### PR DESCRIPTION
**Pull request by FrigoEU**
Hey,

I really like this project and felt like contributing something to get a feel for the codebase. I tried to follow your existing codestyle, but feel free to ask me to change anything/everything. I tried to add the Background component to the RootComponent, but that didn't really work out too well since the text editor needs to be "in between" the background and the rest of the React UI in terms of DOM nodes. I couldn't really figure out how to do it differently, but I'm not really a React expert yet.

Simon

### CODE REVIEW

**Comment by keforbes** [comment]
We have a linter that checks for style errors as part of the build process.  Your commit failed for these (minor) issues:
```
oni/browser/src/UI/Reducer.ts[30, 32]: trailing whitespace
oni/browser/src/UI/Reducer.ts[32, 58]: Missing trailing comma
```

**Comment by FrigoEU** [comment]
Oops, I missed that. Fixed.

**Comment by extr0py** [comment]
Thanks for the kind words on the project! The change looks great to me. 

> I tried to add the Background component to the RootComponent, but that didn't really work out too well since the text editor needs to be "in between" the background and the rest of the React UI in terms of DOM nodes

Yes, this is definitely painful. I like the solution you chose for now - just having ReactDOM.render directly to another element. I'm working on another PR - #303 - which refactors the UI structure a bit, so we end up with something like this:
```
export class RootComponent extends React.Component<IRootComponentProps, void> {

    public render(): JSX.Element {

        return <div className="container vertical full">
            <div className="container full">
                <EditorHost editor={this.props.editor} />
                <Cursor />
                <CursorLine lineType={"line"} />
                <CursorLine lineType={"column"} />
 ...
            </div>
            <div className="container fixed">
                <StatusBar />
            </div>
          </div>
```

Your solution here will fit nicely with that PR because we can just pick up your <Background /> component and place it in the right level there.

**Comment by extr0py** [comment]
Looks great, nice work & thanks for the contribution @FrigoEU ! I'll merge this in.

**Pull request merged**
