### PR TITLE
WIP: #404 - Remove hardcoded PageUp key bindings

### PR DESCRIPTION
**Pull request by extr0py**
As part of this, this would be a good time to sketch out how configurable keybindings could look like on the Oni side (and then later, build optimizations on top of it, along with heavier synching of VimScript keybindings like in #20)

### CODE REVIEW

**Comment by extr0py** [comment]
WIP to Fix #404

**Comment by bert88sta** [comment]
@extr0py 

I think the first thing we need to decide about is whether or not we're going to send keys on a "round trip" or whether oni should intercept bindings it recognizes. On one hand, I like the idea of an init.vim config because our convert to vimkey method doesn't handle complicated bindings well (leader key, for example, which I know for sure I want to be able to use in an oni config for control of UI). On the other hand, there are definitely benefits to be had handling certain actions in-house (not having to come up with a  complicated scheme for interpreting keymappings). I think this is going to clear up well as more UI business becomes externalized

Regardless, the problem above doesn't change my overall thoughts too much. Here's my idea

1) Define a set of actions that a keybinding could take, i.e scrollDown, sendKeyToVim, etc.

2) People can execute a set of actions linearly that they assign to a key. If we're clever and let them send keys to neovim, this allows us to make macros that work across oni and neovim both (!) I might want to do a UI selection and then completion, and then tell neovim to do some manipulation afterwards all in one keybinding.

**Comment by extr0py** [comment]
@bert88sta Yes, good point, I don't think this has been called out explicitly.

> I think the first thing we need to decide about is whether or not we're going to send keys on a "round trip" or whether oni should intercept bindings it recognizes.

Definitely. My plan is to handle the keys directly, for the keys that Oni knows how to handle. This is for a couple of reasons:
- The round-trip through (Neo)Vim incurs a non-negligible delay (10-20ms), so if we can handle it directly, that helps performance.
- There are some features I'd like to implement that would be outside of Neovim. Things like #366.

But Neovim has rich input handling, especially for the text-edit experiences, so for editing, I'd prefer to delegate to Neovim.

I know this is heresy, but I've been looking at the Emacs model for keybindings. Emacs' functional approach combined with key binding is pretty powerful. The JS runtime has the potential to have similiar flexibility. Here's sort of an API I was thinking about:
```
// My plugin.js

const activate = (Oni) => {

    const showRefactorMenu = () => {
        Oni.showPopupMenu(["Extract Method", "Sort Imports", ...], doRefactor)
    }

    const doRefactor = (selectedOption) => {
        // do some refactoring stuff..
    }

    Oni.keys.bind("<C-A-r>", Mode.All, refactor)
}
```

As you mentioned, being able to also send keys to Neovim, or execute a function, would be pretty powerful too. Would just need to expose that in the `Oni` plugin object, which would be straightforward. That hybrid behavior - of doing stuff in Oni and having Neovim manipulate, etc is basically how most of the current UI enhancements are implemented anyway - it makes a lot of sense to expose those to keybindings and plugins, as I'm sure people can think of really creative things to do with that extensibility.

I'd also like to have a way for people more comfortable in the VimScript world to be able to customize the Oni-facing functionality as well - this is sort of along the lines of your #1 suggestion:

```
// Some plugin exposes a 'command' - a named string mapped to the function

const activate = (Oni) => {

    const showRefactorMenu = () => {
        Oni.showPopupMenu(["Extract Method", "Sort Imports", ...], doRefactor)
    }

    const doRefactor = (selectedOption) => {
        // do some refactoring stuff..
    }

    Oni.commands.register("command.refactor")
}

// And then later, in `init.vim`

nnoremap <C-A-r> :call OniCommand("command.refactor", ..someOptionalArgs)
```

I'm holding off on this PR for now, to think through that model a bit more. Let me know if you have any ideas - thanks for your thoughts!

**Comment by bert88sta** [comment]
I think we're definitely in agreement about the functionality of Oni-side
bindings.

This is one of those situations where I'm again going to tout object lookup
as being superior to if or switch statements, especially if we're checking
 hundreds of key chords.

I know that vim round trip is slow, but if I wanted to use my leader key,
(space bar) in a keybind, Say <Space>gb for git blame overlay.  How can we
avoid sending that to neovim?

**Comment by extr0py** [comment]
> I think we're definitely in agreement about the functionality of Oni-side
bindings.

Awesome!

> This is one of those situations where I'm again going to tout object lookup
as being superior to if or switch statements, especially if we're checking
 hundreds of key chords.

Yep, sounds like we're on the same page. Having dynamic / configurable bindings will necessitate object lookup anyway.

> I know that vim round trip is slow, but if I wanted to use my leader key,
(space bar) in a keybind, Say <Space>gb for git blame overlay.  How can we
avoid sending that to neovim?

For this scenario, we might need to have an Oni-side setting for a leader key (and potentially have it sync / integrate with the Vim-side configuration).

**Comment by bert88sta** [comment]
Alright, I'm not sure exactly how neovim does it, but getting a leader key chord is usually based on a timeout IIRC, I'm going to dig through vimdoc and see if I can find more implementation details

**Comment by extr0py** [comment]
No longer needed with #633

**Pull request closed without merging**
