### PR TITLE
Fix #495: Clean up list jumpiness in autocompletion menu

### LINKED ISSUE #495: Jumpy Lists:
I had some feedback about the autocomplete documentation experience:

onicomplete

One thing I noticed, is that it has this particular characteristic that might be suboptimal. That is, when changing the highlighted row in the completion popup, the physical location of *other* items (below it) change. I believe that UIs that don't move elements in lists unless due to scrolling are easier to navigate (unlike accordion style menus), because the user's mental model of where everything is on screen needs to be updated less frequently, or can be updated more quickly.

Scrolling in general doesn't have the same downsides, because all items move in unison - so it only requires that the user understand "every item is where it used to be but moved 10px upwards", which is much more compressed than having to know which items moved upwards, and which moved downwards.

### PR DESCRIPTION
**Pull request by extr0py**
__Issue:__ The autocompletion list is jumpy, so it is a jarring experience for users when the list item changes.

__Fix:__ Move the details to the bottom of the completion menu. I also address another jumping issue - sometimes the autocompletion menu would expand/collapse, which was also a jarring experience. In addition, I made the highlighting a bit more subtle, and added an overflow experience for the details:

completion-v2

### CODE REVIEW

**Comment by extr0py** [comment]
I'll need to fix some issues with the Mouse handling (the `Mouse.ts` strategy is catching all mouse events right now). In addition, I'll need to find a way to expand the completion details, so that users can open the details fully without needing the mouse.

**Comment by extr0py** [comment]
Also need to look at integrating the scrollbar with the quick-info UI.

**Comment by jordwalke** [comment]
Looks pro. I imagine one day being able to map keyboard shortcuts just to scroll the doc browser (which could apply to other scrollable dialogs too).

**Comment by extr0py** [comment]
> I imagine one day being able to map keyboard shortcuts just to scroll the doc browser (which could apply to other scrollable dialogs too).

Definitely! This will be a good case to think about along with #20 and #408.

**Comment by extr0py** [comment]
[ ] Need to fix the mouse interaction and remove the temporary hack

**Pull request merged**
