### PR TITLE
Fix #236, refresh Config object anytime config.js changes, notify any listeners

### LINKED ISSUE #236: Configuration: When config.js changes, trigger a reload of settings
When a user is editing `config.js`, it'd be awesome to see the updates once the user saves. There are a couple of items we'd need for this:

- An event to listen for when configuration changes - like `Config.on("changed", (newConfig) => { ... })`
- A config file listener in Config that watches for file changes (or the save event on config.js) and reloads the new settings
- Updated the places that care about settings / setting changes to opt-in to listening for these. An example might be for the cursorLine/cursorColumn functionality

### PR DESCRIPTION
**Pull request by keforbes**
Refactored #294 following @extr0py's suggestions.  `Config` is now a class accessed via singleton and uses `EventEmitter`.  This required changing every class that uses `Config` to fetch the singleton first.

### CODE REVIEW

**Comment by extr0py** [comment]
Nice! I tried this out and it works well. Cool to see the results instantly when changing the fonts or the cursorLine settings. Thanks for investigating this and doing the refactor!

**Comment by extr0py** [comment]
I'll bring in this PR. Check out the bounty and let me know how easy it is to claim it:
https://www.bountysource.com/issues/42243372-configuration-when-config-js-changes-trigger-a-reload-of-settings

Thanks @keforbes !

**Comment by keforbes** [comment]
Ok, I tried claiming the bounty.  I had to create an account with bountysource to claim it and now I guess you have to approve it.

**Comment by extr0py** [comment]
I approved it! Hopefully it went through

**Pull request merged**
